### ISSUE TITLE
how to start ？

### ISSUE THREAD

**Issue by ucasiggcas** [nevosegal/cnn-qmul#1]
Dear,

In your project,
I don't know what is the yaml file ?is it useful ?
If I only have the wav files with different instruments ,could I run the project ?

**Comment by ucasiggcas** [comment]
In your serialize_dataset.py
I only see the `lr.feature.melspectrogram` as the feature,is it useful ?

Now to recognize the instrument is just like to recognize the speaker,
you maybe know the VoicePrint Recognition, and there are many other feature could be used,
such as i-vector ,etc

**Comment by nevosegal** [comment]
Hey @ucasiggcas! This was a university project from a few years ago :) It is no longer maintained and was not written for anyone other than me to use it - sorry! I may pick it up again later, but currently I don't have time.
